@extends('layouts.app')
@section('title','Shipments')
@section('content')
@php
$badge=['scheduled'=>'bg-blue-100 text-blue-800 ring-blue-200','in_transit'=>'bg-purple-100 text-purple-800 ring-purple-200','delivered'=>'bg-green-100 text-green-800 ring-green-200','cancelled'=>'bg-red-100 text-red-800 ring-red-200'];
@endphp
<div class="space-y-6">
 <div class="flex justify-between items-start gap-4"><div><h2 class="text-2xl font-bold">Shipments</h2><p class="text-sm text-gray-600">Track shipment execution and delivery status.</p></div><a href="{{ route('shipments.create') }}" class="rounded-lg bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Add Shipment</a></div>
 <form method="GET" class="rounded-xl border bg-white p-4 shadow-sm">
  <div class="grid grid-cols-1 gap-3 md:grid-cols-4"><input name="search" value="{{ $search ?? '' }}" placeholder="Search shipment, SO, customer, vehicle, route" class="md:col-span-2 rounded-lg border-gray-300"><select name="status" class="rounded-lg border-gray-300"><option value="">All Statuses</option><option value="scheduled" @selected(($status ?? '')==='scheduled')>Scheduled</option><option value="in_transit" @selected(($status ?? '')==='in_transit')>In Transit</option><option value="delivered" @selected(($status ?? '')==='delivered')>Delivered</option><option value="cancelled" @selected(($status ?? '')==='cancelled')>Cancelled</option></select><div class="flex gap-2"><button class="flex-1 rounded-lg bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Filter</button><a href="{{ route('shipments.index') }}" class="rounded-lg border px-4 py-2 text-sm font-semibold">Reset</a></div></div>
 </form>
 <div class="overflow-x-auto rounded-xl border bg-white shadow-sm"><table class="min-w-full divide-y text-sm"><thead class="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th class="px-4 py-3">Shipment</th><th class="px-4 py-3">Sales Order</th><th class="px-4 py-3">Customer</th><th class="px-4 py-3">Vehicle</th><th class="px-4 py-3">Driver</th><th class="px-4 py-3">Date</th><th class="px-4 py-3">Route</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Action</th></tr></thead><tbody class="divide-y">@forelse($shipments as $shipment)<tr><td class="px-4 py-3 font-medium">{{ $shipment->shipment_number }}</td><td class="px-4 py-3">{{ $shipment->salesOrder->so_number ?? '-' }}</td><td class="px-4 py-3">{{ $shipment->salesOrder->customer->name ?? '-' }}</td><td class="px-4 py-3">{{ $shipment->vehicle_number ?? '-' }}</td><td class="px-4 py-3">{{ $shipment->driver_name ?? '-' }}</td><td class="px-4 py-3">{{ $shipment->shipment_date }}</td><td class="px-4 py-3">{{ $shipment->origin ?? '-' }} - {{ $shipment->destination ?? '-' }}</td><td class="px-4 py-3"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-semibold capitalize ring-1 ring-inset {{ $badge[$shipment->status] ?? 'bg-gray-100 text-gray-800 ring-gray-200' }}">{{ str_replace('_',' ',$shipment->status) }}</span></td><td class="px-4 py-3 text-right"><a class="text-blue-600" href="{{ route('shipments.show',$shipment) }}">View</a> <a class="text-yellow-600" href="{{ route('shipments.edit',$shipment) }}">Edit</a></td></tr>@empty<tr><td colspan="9" class="px-4 py-8 text-center text-gray-500">No shipments match your filter.</td></tr>@endforelse</tbody></table></div>
 <div>{{ $shipments->links() }}</div>
</div>
@endsection
