@extends('layouts.app')
@section('title', 'Coal Products')
@section('content')
<div class="space-y-6">
 <div class="flex justify-between items-start gap-4"><div><h2 class="text-2xl font-bold">Coal Products</h2><p class="text-sm text-gray-600">Manage coal product specifications and stock quantity.</p></div><a href="{{ route('coal-products.create') }}" class="rounded-lg bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Add Coal Product</a></div>
 <form method="GET" class="rounded-xl border bg-white p-4 shadow-sm"><div class="flex flex-col gap-3 sm:flex-row"><input name="search" value="{{ $search ?? '' }}" placeholder="Search product code, name, grade, or unit" class="flex-1 rounded-lg border-gray-300"><button class="rounded-lg bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Search</button><a href="{{ route('coal-products.index') }}" class="rounded-lg border px-4 py-2 text-sm font-semibold">Reset</a></div></form>
 <div class="overflow-x-auto rounded-xl border bg-white shadow-sm"><table class="min-w-full divide-y text-sm"><thead class="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th class="px-4 py-3">Product Code</th><th class="px-4 py-3">Name</th><th class="px-4 py-3">Grade</th><th class="px-4 py-3">Calorific Value</th><th class="px-4 py-3">Sulfur Content</th><th class="px-4 py-3">Ash Content</th><th class="px-4 py-3">Stock Qty</th><th class="px-4 py-3">Unit</th><th class="px-4 py-3 text-right">Action</th></tr></thead><tbody class="divide-y">@forelse($coalProducts as $product)<tr><td class="px-4 py-3 font-medium">{{ $product->product_code }}</td><td class="px-4 py-3">{{ $product->name }}</td><td class="px-4 py-3">{{ $product->grade ?? '-' }}</td><td class="px-4 py-3">{{ $product->calorific_value ?? '-' }}</td><td class="px-4 py-3">{{ $product->sulfur_content ?? '-' }}</td><td class="px-4 py-3">{{ $product->ash_content ?? '-' }}</td><td class="px-4 py-3">{{ number_format($product->stock_qty, 2) }}</td><td class="px-4 py-3">{{ $product->unit }}</td><td class="px-4 py-3 text-right"><div class="flex justify-end gap-2"><a class="text-blue-600" href="{{ route('coal-products.show', $product) }}">View</a><a class="text-yellow-600" href="{{ route('coal-products.edit', $product) }}">Edit</a><form method="POST" action="{{ route('coal-products.destroy', $product) }}" onsubmit="return confirm('Delete this coal product?')">@csrf @method('DELETE')<button class="text-red-600">Delete</button></form></div></td></tr>@empty<tr><td colspan="9" class="px-4 py-8 text-center text-gray-500">No coal products match your search.</td></tr>@endforelse</tbody></table></div><div>{{ $coalProducts->links() }}</div>
</div>
@endsection
