@extends('layouts.app')
@section('title','Stock Movements')
@section('content')
<div class="space-y-6">
 <div><h2 class="text-2xl font-bold">Stock Movements</h2><p class="text-sm text-gray-600">Review inbound and outbound stock history.</p></div>
 <form method="GET" class="rounded-xl border bg-white p-4 shadow-sm"><div class="grid grid-cols-1 gap-3 md:grid-cols-4"><input name="search" value="{{ $search ?? '' }}" placeholder="Search reference or description" class="md:col-span-2 rounded-lg border-gray-300"><select name="type" class="rounded-lg border-gray-300"><option value="">All Types</option><option value="in" @selected(($type ?? '')==='in')>Inbound</option><option value="out" @selected(($type ?? '')==='out')>Outbound</option></select><div class="flex gap-2"><button class="flex-1 rounded-lg bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Filter</button><a href="{{ route('stock-movements.index') }}" class="rounded-lg border px-4 py-2 text-sm font-semibold">Reset</a></div></div></form>
 <div class="overflow-x-auto rounded-xl border bg-white shadow-sm"><table class="min-w-full divide-y text-sm"><thead class="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th class="px-4 py-3">Date</th><th class="px-4 py-3">Coal Product</th><th class="px-4 py-3">Type</th><th class="px-4 py-3">Quantity</th><th class="px-4 py-3">Reference Type</th><th class="px-4 py-3">Reference ID</th><th class="px-4 py-3">Description</th><th class="px-4 py-3 text-right">Action</th></tr></thead><tbody class="divide-y">@forelse($stockMovements as $movement)<tr><td class="px-4 py-3">{{ $movement->created_at }}</td><td class="px-4 py-3">{{ $movement->coalProduct->name ?? '-' }}</td><td class="px-4 py-3"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $movement->type === 'in' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700' }}">{{ $movement->type === 'in' ? 'Inbound' : 'Outbound' }}</span></td><td class="px-4 py-3">{{ number_format($movement->quantity,2) }}</td><td class="px-4 py-3">{{ $movement->reference_type }}</td><td class="px-4 py-3">{{ $movement->reference_id }}</td><td class="px-4 py-3">{{ $movement->description ?? '-' }}</td><td class="px-4 py-3 text-right"><a class="text-blue-600" href="{{ route('stock-movements.show',$movement) }}">View</a></td></tr>@empty<tr><td colspan="8" class="px-4 py-8 text-center text-gray-500">No stock movements match your filter.</td></tr>@endforelse</tbody></table></div><div>{{ $stockMovements->links() }}</div>
</div>
@endsection
